### ISSUE TITLE
Tycho 2.7.5 + Domain + Wizard dont work on J17

### ISSUE THREAD

**Issue by cdietrich** [eclipse-xtext/xtext#2849]
Tycho 2.7.5 + Domain + Wizard dont work on J17

 Caused by: java.lang.ClassNotFoundException: org.apache.maven.surefire.junit4.JUnit4Provider
	at org.eclipse.tycho.surefire.osgibooter.CombinedClassLoader.findClass(CombinedClassLoader.java:39)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at org.apache.maven.surefire.util.ReflectionUtils.loadClass(ReflectionUtils.java:241)
	... 19 more

**Comment by cdietrich** [comment]
https://github.com/eclipse/mwe/issues/275

**Comment by cdietrich** [comment]
still does not work  in integ test crap :(

**Comment by cdietrich** [comment]
might also be a flakyness on github actions

**Comment by LorenzoBettini** [comment]
What's the problem?

**Comment by cdietrich** [comment]
2nd attempt worker but log is still full of warnings

**Comment by cdietrich** [comment]
@szarnekow @LorenzoBettini can someone look into
https://github.com/xtext/xtext-reference-projects/actions/runs/6926300643
is there a way to get screenshots from gh actions?

**Comment by LorenzoBettini** [comment]
@cdietrich if you mean screenshots generated by SWTBot, this is how I do https://github.com/eclipse-emf-parsley/emf-parsley/blob/master/.github/workflows/maven.yml#L61

**Comment by cdietrich** [comment]
Yes I mean these

**Comment by LorenzoBettini** [comment]
concerning the failing test: I'd increase the SWTBot timeout (e.g., `-Dorg.eclipse.swtbot.search.timeout=20000`), and/or I'd also use flaky test support from Maven/Tycho, how we do in Xtext https://github.com/eclipse/xtext/blob/main/.mvn/maven.config#L3 or how I do in EMF Parsley https://github.com/eclipse-emf-parsley/emf-parsley/blob/master/releng/org.eclipse.emf.parsley.parent/pom.xml#L810C9-L810C9

**Comment by cdietrich** [comment]
Can you provide pr

**Comment by LorenzoBettini** [comment]
OK, later today.
Do you have any preference for the solutions?
I don't remember well how those projects were structured, I hope I find my way ;)

**Comment by cdietrich** [comment]
There is only one swt project bellow integration tests

**Comment by cdietrich** [comment]
still flaky.

https://github.com/xtext/xtext-reference-projects/compare/cd_refresh?expand=1

maybe you can also find some time to have a look
@LorenzoBettini @szarnekow

**Comment by LorenzoBettini** [comment]
Shall we close this as well?
