### ISSUE TITLE
AutoEdit tests started to fail

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse-xtext/xtext#3285]
Maybe something has changed in platform?

**Comment by cdietrich** [comment]
maybe https://github.com/eclipse-platform/eclipse.platform.ui/commit/7adb4efefcb405435fc83526ed7b8280fb63290e#diff-a37ba54e0a891e8a3bf10abe924cdb174e013ec2d601721d31438e8cf5a7d86e

**Comment by LorenzoBettini** [comment]
Any idea on how to fix that?

**Comment by cdietrich** [comment]
Don’t have time to digg
Does the new behavior make sense? Maybe we can conditionally adjust expectation 
Maybe discuss on Tuesday

**Comment by szarnekow** [comment]
I commented on the PR in platform. The behavior cannot be overridden right now. Let’s see what they will do about it

**Comment by LorenzoBettini** [comment]
I seem to understand that this is fixed now, isn't it?

**Comment by cdietrich** [comment]
looks like.
