### ISSUE TITLE
Domain Model Integ Test fails

### ISSUE THREAD

**Issue by cdietrich** [eclipse-xtext/xtext#3294]
https://github.com/xtext/xtext-reference-projects/actions/runs/12347848620/job/34455626438

**Comment by LorenzoBettini** [comment]
the errors should definitely be printed when they happen

**Comment by cdietrich** [comment]
see https://github.com/xtext/xtext-reference-projects/issues/459

**Comment by LorenzoBettini** [comment]
This does not fail anymore, does it?

**Comment by cdietrich** [comment]
No it does not

**Comment by LorenzoBettini** [comment]
so we can close it.

**Comment by LorenzoBettini** [comment]
yes, I'll have a look at that in the context of the linked issue https://github.com/xtext/xtext-reference-projects/issues/459
